### ISSUE TITLE
Command line args

### ISSUE THREAD

**Issue by Phred7** [MSURoboCats/robotCode#14]
When running run_robot.py, main should allow for a bool via the command line that defaults to False. This bool will determine if the GUI/Testing Code will be run.

**Comment by SarthakatSJSU** [comment]
Hey 
Is this issue still open or can it be assigned ?

**Comment by Sarthakischauhan** [comment]
Hey
Is this issue still open and can it be assigned ?

**Comment by Phred7** [comment]
> Hey Is this issue still open and can it be assigned?
Yes, this issue is still open and can be assigned however, it can only be assigned to members of this oprganization.

**Comment by Sarthakischauhan** [comment]
Okay, so i can't work on it right ?

**Comment by Phred7** [comment]
Correct @Sarthakischauhan
